export const prData = [
    {img: 'https://github.com/torvalds.png', repoName: 'Flask_Chat_App', prId: '1', title: 'Update README.md', requesterName: 'John Doe', requestedTime: 'June 20, 2024 at 08:34:13 PM', prStatus: 'Merged' },
    {img: 'https://github.com/gaearon.png', repoName: 'Flask_Chat_App', prId: '2', title: 'Fix bug in login', requesterName: 'Jane Smith', requestedTime: 'June 21, 2024 at 10:15:42 AM', prStatus: 'Pending' },
    {img: 'https://github.com/sindresorhus.png', repoName: 'Flask_Chat_App', prId: '3', title: 'Add new feature', requesterName: 'Alice Johnson', requestedTime: 'June 22, 2024 at 02:21:30 PM', prStatus: 'Merged' },
    {img: 'https://github.com/yyx990803.png', repoName: 'Flask_Chat_App', prId: '4', title: 'Refactor codebase', requesterName: 'Bob Brown', requestedTime: 'June 23, 2024 at 11:45:10 AM', prStatus: 'Merged' },
    {img: 'https://github.com/getify.png', repoName: 'Flask_Chat_App', prId: '5', title: 'Improve performance', requesterName: 'Charlie Davis', requestedTime: 'June 24, 2024 at 03:05:28 PM', prStatus: 'Pending' },
    {img: 'https://github.com/addyosmani.png', repoName: 'Flask_Chat_App', prId: '6', title: 'Fix typos', requesterName: 'Diana Miller', requestedTime: 'June 25, 2024 at 09:14:50 AM', prStatus: 'Merged' },
    {img: 'https://github.com/torvalds.png', repoName: 'repo7', prId: '7', title: 'Add unit tests', requesterName: 'Ethan Wilson', requestedTime: 'June 26, 2024 at 04:50:32 PM', prStatus: 'Merged' },
    {img: 'https://github.com/tj.png', repoName: 'repo8', prId: '8', title: 'Update dependencies', requesterName: 'Fiona Martinez', requestedTime: 'June 27, 2024 at 07:22:14 AM', prStatus: 'Pending' },
    {img: 'https://github.com/jashkenas.png', repoName: 'repo9', prId: '9', title: 'Improve UI', requesterName: 'George Anderson', requestedTime: 'June 28, 2024 at 08:30:55 PM', prStatus: 'Merged' },
    {img: 'https://github.com/rauchg.png', repoName: 'repo10', prId: '10', title: 'Fix security issue', requesterName: 'Hannah Thomas', requestedTime: 'June 29, 2024 at 10:12:11 AM', prStatus: 'Merged' },
    {img: 'https://github.com/paulirish.png', repoName: 'repo11', prId: '11', title: 'Optimize database', requesterName: 'Ian White', requestedTime: 'June 30, 2024 at 01:34:40 PM', prStatus: 'Pending' },
    {img: 'https://github.com/bkeepers.png', repoName: 'repo12', prId: '12', title: 'Improve accessibility', requesterName: 'Jack Harris', requestedTime: 'July 1, 2024 at 06:45:27 PM', prStatus: 'Merged' },
    {img: 'https://github.com/mdo.png', repoName: 'repo13', prId: '13', title: 'Add dark mode', requesterName: 'Karen Clark', requestedTime: 'July 2, 2024 at 09:05:58 AM', prStatus: 'Merged' },
    {img: 'https://github.com/dhh.png', repoName: 'repo14', prId: '14', title: 'Update documentation', requesterName: 'Leo Lewis', requestedTime: 'July 3, 2024 at 11:15:34 AM', prStatus: 'Pending' },
    {img: 'https://github.com/holman.png', repoName: 'repo15', prId: '15', title: 'Fix CSS issues', requesterName: 'Mia Robinson', requestedTime: 'July 4, 2024 at 02:25:41 PM', prStatus: 'Merged' },
    {img: 'https://github.com/mxcl.png', repoName: 'repo16', prId: '16', title: 'Add new API endpoint', requesterName: 'Noah Walker', requestedTime: 'July 5, 2024 at 03:14:55 PM', prStatus: 'Merged' },
    {img: 'https://github.com/fat.png', repoName: 'repo17', prId: '17', title: 'Improve logging', requesterName: 'Olivia Hall', requestedTime: 'July 6, 2024 at 07:45:13 AM', prStatus: 'Pending' },
    {img: 'https://github.com/jaredhanson.png', repoName: 'repo18', prId: '18', title: 'Update build script', requesterName: 'Paul Young', requestedTime: 'July 7, 2024 at 09:30:29 PM', prStatus: 'Pending' },
    {img: 'https://github.com/leebyron.png', repoName: 'repo19', prId: '19', title: 'Enhance security', requesterName: 'Quinn King', requestedTime: 'July 8, 2024 at 11:45:12 AM', prStatus: 'Merged' },
    {img: 'https://github.com/bvaughn.png', repoName: 'repo20', prId: '20', title: 'Improve error handling', requesterName: 'Rachel Wright', requestedTime: 'July 9, 2024 at 02:34:17 PM', prStatus: 'Pending' },
    {img: 'https://github.com/haacked.png', repoName: 'repo21', prId: '21', title: 'Refactor authentication', requesterName: 'Samuel Green', requestedTime: 'July 10, 2024 at 06:14:25 PM', prStatus: 'Pending' },
    {img: 'https://github.com/sdras.png', repoName: 'repo22', prId: '22', title: 'Add caching', requesterName: 'Tina Hill', requestedTime: 'July 11, 2024 at 08:50:32 AM', prStatus: 'Merged' },
    {img: 'https://github.com/gaearon.png', repoName: 'repo23', prId: '23', title: 'Update styles', requesterName: 'Uma Scott', requestedTime: 'July 12, 2024 at 10:23:45 AM', prStatus: 'Pending' },
    {img: 'https://github.com/rauchg.png', repoName: 'repo24', prId: '24', title: 'Optimize images', requesterName: 'Victor Adams', requestedTime: 'July 13, 2024 at 01:11:09 PM', prStatus: 'Pending' },
    {img: 'https://github.com/yyx990803.png', repoName: 'repo25', prId: '25', title: 'Improve SEO', requesterName: 'Wendy Baker', requestedTime: 'July 14, 2024 at 04:32:17 PM', prStatus: 'Merged' }
];
